### ISSUE TITLE
How to play

### ISSUE THREAD

**Issue by Falling10fruit** [cooldudes24/untitled1#1]
Which files am I supposed to download to play this game.

**Comment by cooldudes24** [comment]
It's not finished at all . . . . not even playable, sadly.

**Comment by Falling10fruit** [comment]
Then how did you get the footage of it and shared it to us.

**Comment by Falling10fruit** [comment]
Oh nevermind, I found out how. (Dowload everything and run the python code)

**Comment by Falling10fruit** [comment]
That's a pretty cool game
